{{ if .Values.service.postgres }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}postgres
  name: {{ .Values.resourcePrefix }}postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.service: {{ .Values.resourcePrefix }}postgres
status:
  loadBalancer: {}
{{ end }}
