{{- with .Values.docker.services.postgres }}
{{- if hasKey $.Values.service "postgres" | ternary $.Values.service.postgres .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ $.Values.resourcePrefix }}postgres
  name: {{ $.Values.resourcePrefix }}postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.service: {{ $.Values.resourcePrefix }}postgres
status:
  loadBalancer: {}
{{- end }}
{{- end }}
