{{- with .Values.docker.services.mysql }}
{{- if hasKey $.Values.service "mysql" | ternary $.Values.service.mysql .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mysql
    app.service: {{ $.Values.resourcePrefix }}mysql
  name: {{ $.Values.resourcePrefix }}mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app.service: {{ $.Values.resourcePrefix }}mysql
status:
  loadBalancer: {}
{{- end }}
{{- end }}
