FROM {{ @('docker.repository')}}:{{ @('docker.tagPrefix') }}{{ @('app.version') }} AS source
LABEL build="{{ @('namespace') ~ ':' ~ @('app.version') }}"

FROM scratch

{% if @('app.bundle_certs') == 'yes' %}
COPY --from=source /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
{% endif %}

COPY --chown=0:0 --from=source /go/bin/{{ @('app.binary') }} /

{% for binaryPath in @('app.additional_binaries') %}
COPY --chown=0:0 --from=source /{{ binaryPath }} /{{ binaryPath }}
{% endfor %}

ENTRYPOINT ["/{{ @('app.binary') }}"]
EXPOSE {{ @('app.default_port.port') }}
EXPOSE {{ @('app.health_port') }}
