FROM {{ @('docker.repository')}}:{{ @('docker.tagPrefix') }}{{ @('app.version') }} AS source

FROM scratch

COPY --chown=0:0 --from=source /go/bin/{{ @('app.binary') }} /
ENTRYPOINT ["/{{ @('app.binary') }}"]
EXPOSE {{ @('app.port') }}
EXPOSE {{ @('app.health_port') }}
