function('built_images', [services]): |
  #!php
  $builtImages = [];
  foreach ($services as $service) {
    if ($service['image'] && count($service['upstream']) > 0) {
      $builtImages[] = $service['image'];
    }
  }
  $allImages = explode("\n", shell_exec('docker image ls -a --format \'{{ print .Repository ":" .Tag }}\''));
  # workspace commands don't allow non-string types
  = join(' ', array_intersect($builtImages, $allImages));

command('cleanup built-images'):
  env:
    BUILD_LABEL: = @('namespace') ~ ':' ~ @('app.version')
    IMAGES: = built_images(docker_service_images(@('docker.compose.bin')))
  exec: |
    #!bash
    IMAGES=($IMAGES)
    if [ "${#IMAGES[@]}" -gt 0 ]; then
      run docker image rm --force -- "${IMAGES[@]}"
    fi
    run docker image prune --force --filter=label=build="$BUILD_LABEL"
    [ -z "$(docker builder 2>&1)" ] || run docker builder prune --force --filter=label=build="$BUILD_LABEL"
