confd('harness:/'):
  - { src: application/overlay/Jenkinsfile }
  - { src: application/skeleton/go.mod }
  - { src: application/skeleton/README.md }
  - { src: application/skeleton/.gitignore }
  - { src: docker/image/app/Dockerfile }
  - { src: docker/image/app/Dockerfile.prod }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: helm/app/Chart.yaml }
  - { src: helm/app/values.yaml }
  - { src: helm/qa/Chart.yaml }
  - { src: helm/qa/requirements.yaml }
  - { src: helm/qa/values.yaml }
