confd('harness:/'):
  - { src: application/overlay/Jenkinsfile }
  - { src: application/skeleton/README.md }
  - { src: application/skeleton/.gitignore }
  - { src: docker/image/app/Dockerfile }
  - { src: docker/image/app/root/lib/task/gocyclo.sh }
  - { src: docker/image/app/root/lib/task/gosec.sh }
  - { src: docker/image/app/root/lib/task/fmt/check.sh }
  - { src: docker/image/app/root/lib/task/modules/after.sh }
  - { src: docker/image/app/root/lib/task/modules/before.sh }
  - { src: docker/image/app/root/lib/task/modules/check.sh }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: harness/scripts/mod_init.sh }
  - { src: harness/scripts/init.sh }
  - { src: harness/scripts/integration/run.sh }
  - { src: harness/scripts/integration/run-one.sh }
  - { src: helm/app/Chart.yaml }
  - { src: helm/app/values.yaml }
  - { src: helm/app/values-production.yaml }
  - { src: helm/app/values-preview.yaml }
  - { src: helm/qa/Chart.yaml }
  - { src: helm/qa/requirements.yaml }
  - { src: helm/qa/values.yaml }
