after('harness.install'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
  exec: |
    #!bash(workspace:/)
    ws enable
    docker cp $(docker-compose -p ${COMPOSE_PROJECT_NAME} ps -q app):/app/go.sum ./go.sum

after('harness.refresh'): |
  #!bash(harness:/)|@
  run docker-compose -p @('namespace') stop
  run docker-compose -p @('namespace') pull
  run docker-compose -p @('namespace') up -d --build
