after('harness.install'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    COMPOSE_PROJECT_NAME: = @('namespace')
  exec: |
    #!bash(workspace:/)
    source .my127ws/harness/scripts/apply.sh
    source .my127ws/harness/scripts/init.sh
    ws enable

after('harness.refresh'): 
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    COMPOSE_PROJECT_NAME: = @('namespace')
  exec: |
    #!bash(harness:/)|@
    run $COMPOSE_BIN stop
    run $COMPOSE_BIN pull
    run $COMPOSE_BIN up -d --build
