before('harness.install'): |
  #!bash(workspace:/)
  rsync --exclude='*.twig' --exclude='_twig' -a .my127ws/application/skeleton/ .

after('harness.install'): |
  #!bash
  docker cp $(docker-compose ps -q app):/app/go.sum ./go.sum
  ws enable

after('harness.refresh'): |
  #!bash(harness:/)|@
  run docker-compose -p @('namespace') stop
  run docker-compose -p @('namespace') pull
  run docker-compose -p @('namespace') up -d --build
