after('harness.install'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
  exec: |
    #!bash(workspace:/)
    chmod +x .my127ws/harness/scripts/mod_init.sh
    run docker run --rm -v "$(pwd):/app" -w /app golang:1.15 ./.my127ws/harness/scripts/mod_init.sh
    source .my127ws/harness/scripts/apply.sh
    run ws enable

after('harness.refresh'): |
  #!bash(harness:/)|@
  run docker-compose -p @('namespace') stop
  run docker-compose -p @('namespace') pull
  run docker-compose -p @('namespace') up -d --build
