apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}app
  labels:
    app.service: {{ .Values.resourcePrefix }}app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}app
  template:
    metadata:
      labels:
        app.service: {{ .Values.resourcePrefix }}app
    spec:
      enableServiceLinks: false
      containers:
      - name: app
        env:
        {{- range $key, $value := .Values.docker.services.app.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.docker.services.app.environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ .Values.resourcePrefix }}app
        {{- end }}
        image: {{ .Values.docker.image.app }}
        imagePullPolicy: Always
        ports:
        {{- include "container.ports" . | indent 8 }}
        resources: {}
        {{- include "probes" . | indent 8 }}
{{- if .Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always
status: {}
