apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}app
  labels:
    app.service: {{ .Values.resourcePrefix }}app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}app
  template:
    metadata:
      labels:
        app.service: {{ .Values.resourcePrefix }}app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: {{ quote .Values.default_port.port }}
    spec:
      containers:
      - env:
        {{- range $key, $value := .Values.docker.services.app.environment }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        image: {{ .Values.docker.image.app }}
        imagePullPolicy: Always
        name: app
        ports:
        {{- include "container.ports" . | indent 8 }}
        resources: {}
        {{- include "probes" . | indent 8 }}
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}docker-config
      restartPolicy: Always
status: {}
