{{ if eq .Values.ingress.type "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
{{- end }}
  creationTimestamp: null
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: app
{{- if .Values.ingress.protocol }}
    ingress.kubernetes.io/protocol: {{ .Values.ingress.protocol }}
{{- end }}
    app.service: {{ .Values.resourcePrefix }}app
  name: {{ .Values.resourcePrefix }}app
spec:
  rules:
  - host: {{ .Values.docker.services.app.environment.APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.resourcePrefix }}app
          servicePort: {{ .Values.default_port.port }}
{{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
status:
  loadBalancer: {}
{{ end }}
