{{ if eq .Values.ingress.type "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
{{- if .Values.ingress.protocol }}  
    ingress.kubernetes.io/protocol: {{ .Values.ingress.protocol }}
{{- end }}
    app.service: {{ .Values.resourcePrefix }}app
  name: {{ .Values.resourcePrefix }}app
spec:
  rules:
  - host: {{ .Values.docker.services.app.environment.APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.resourcePrefix }}app
          servicePort: {{ .Values.default_port.port }}
status:
  loadBalancer: {}
{{ end }}
