{{ if eq .Values.ingress.type "standard" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
{{- end }}
  creationTimestamp: null
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: app
{{- if .Values.ingress.protocol }}
    ingress.kubernetes.io/protocol: {{ .Values.ingress.protocol }}
{{- end }}
    app.service: {{ .Values.resourcePrefix }}app
  name: {{ .Values.resourcePrefix }}app
spec:
  {{- with (pick .Values.ingress "ingressClassName" "tls") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  rules:
  - host: {{ .Values.docker.services.app.environment.APP_HOST }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.resourcePrefix }}app
            port:
              number: {{ .Values.default_port.port }}
status:
  loadBalancer: {}
{{ end }}
