{{ if eq .Values.ingress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-{{ .Values.resourcePrefix }}app-virtualservice
 labels:
   app: {{ .Values.resourcePrefix }}app
   app.service: {{ .Values.resourcePrefix }}app
spec:
 hosts:
 - {{ .Values.docker.services.app.environment.APP_HOST }}
 gateways:
 - istio-system/{{ .Release.Namespace }}-gateway
 http:
 - route:
   - destination:
       host: {{ .Values.resourcePrefix }}app
       port:
         number: {{ .Values.port }}
{{ end }}
