{{- with .Values.docker.services.app }}
{{- if and $.Values.prometheus.podMonitoring .enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $.Values.resourcePrefix }}app
  labels:
    app.service: {{ $.Values.resourcePrefix }}app
spec:
  selector:
    matchLabels:
      app.service: {{ $.Values.resourcePrefix }}app
  podMetricsEndpoints:
{{- if .metricsEnabled -}}
{{ .metricsEndpoints | toYaml | nindent 6 -}}
{{- end }}
{{- end }}
{{- end }}
