{{- with .Values.docker.services.app }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: app
    app.service: {{ $.Values.resourcePrefix }}app
  name: {{ $.Values.resourcePrefix }}app
spec:
  ports:
  - name: "{{ $.Values.default_port.name | default $.Values.default_port.port }}"
    port: {{ $.Values.default_port.port }}
    targetPort: {{ $.Values.default_port.port }}
{{- if $.Values.default_port.protocol }}
    protocol: {{ $.Values.default_port.protocol | quote }}
{{- end }}
  selector:
    app.service: {{ $.Values.resourcePrefix }}app
status:
  loadBalancer: {}
{{- end }}
{{- end }}
