apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}app
  name: {{ .Values.resourcePrefix }}app
spec:
  ports:
  - name: "{{ .Values.port }}"
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app.service: {{ .Values.resourcePrefix }}app
status:
  loadBalancer: {}
